config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import redirect
from django.urls import include, path
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from rest_framework.authtoken.views import obtain_auth_token


def favicon(request):
    return redirect(
        staticfiles_storage.url("images/favicons/favicon.ico"),
        permanent=True,
    )


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("svaudio.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("activity/", include("actstream.urls")),
    path("comments/", include("django_comments.urls")),
    # Redirect to favicon
    path("favicon.ico", favicon),
    # Your stuff: custom urls includes go here
    path("", include("svaudio.artists.urls", namespace="artists")),
    path("", include("svaudio.repo.urls", namespace="repo")),
    path("", include("svaudio.tags.urls", namespace="tags")),
    path("claims/", include("svaudio.claims.urls", namespace="claims")),
    # Flatpages go last
    path("", flatpages_views.flatpage, {"url": "/"}, name="home"),
    path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # GraphQL base url
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

svaudio/artists/urls.py
from django.urls import path

from svaudio.artists.views import artists_list_view

app_name = "artists"
urlpatterns = [
    path("artists/", view=artists_list_view, name="artist-list"),
]

svaudio/claims/urls.py
from django.urls import path

from .views import (
    moderate_action_view,
    moderate_view,
    object_claim_create_view,
    object_claim_list_view,
)

app_name = "claims"
urlpatterns = [
    path(
        "moderate/",
        view=moderate_view,
        name="moderate",
    ),
    path(
        "moderate/~action/",
        view=moderate_action_view,
        name="moderate-action",
    ),
    path(
        "<int:content_type_id>/<int:object_id>/",
        view=object_claim_list_view,
        name="object-claim-list",
    ),
    path(
        "<int:content_type_id>/<int:object_id>/~create/",
        view=object_claim_create_view,
        name="object-claim-create",
    ),
]

svaudio/repo/urls.py
from django.urls import path

from svaudio.repo.views import (
    location_submit_api_view,
    location_submit_view,
    module_add_tag_view,
    module_detail_view,
    module_list_view,
    module_remove_tagged_item_view,
    module_update_view,
    project_add_tag_view,
    project_detail_view,
    project_list_view,
    project_remove_tagged_item_view,
    project_update_view,
)

app_name = "repo"
urlpatterns = [
    path(
        "locations/submit/",
        view=location_submit_view,
        name="location-submit",
    ),
    path(
        "locations/submit/api/",
        view=location_submit_api_view,
        name="location-submit-api",
    ),
    path(
        "modules/",
        view=module_list_view,
        name="module-list",
    ),
    path(
        "modules/<str:hash>/",
        view=module_detail_view,
        name="module-detail",
    ),
    path(
        "modules/<str:hash>/~add-tag/",
        view=module_add_tag_view,
        name="module-add-tag",
    ),
    path(
        "modules/<str:hash>/~remove-tagged-item/",
        view=module_remove_tagged_item_view,
        name="module-remove-tagged-item",
    ),
    path(
        "modules/<str:hash>/~update/",
        view=module_update_view,
        name="module-update",
    ),
    path(
        "projects/",
        view=project_list_view,
        name="project-list",
    ),
    path(
        "projects/<str:hash>/",
        view=project_detail_view,
        name="project-detail",
    ),
    path(
        "projects/<str:hash>/~add-tag/",
        view=project_add_tag_view,
        name="project-add-tag",
    ),
    path(
        "projects/<str:hash>/~remove-tagged-item/",
        view=project_remove_tagged_item_view,
        name="project-remove-tagged-item",
    ),
    path(
        "projects/<str:hash>/~update/",
        view=project_update_view,
        name="project-update",
    ),
]

svaudio/tags/urls.py
from django.urls import path

from svaudio.tags.views import tag_detail_view, tag_list_view

app_name = "tags"
urlpatterns = [
    path(
        "tags/",
        view=tag_list_view,
        name="tag-list",
    ),
    path(
        "tags/<str:slug>/",
        view=tag_detail_view,
        name="tag-detail",
    ),
]

svaudio/users/urls.py
from django.urls import path

from svaudio.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

svaudio/claims/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models as m
from django.utils.translation import gettext_lazy as _

from svaudio.users.models import User


class Claim(m.Model):
    created_at = m.DateTimeField(auto_now_add=True)
    user = m.ForeignKey(
        User,
        on_delete=m.CASCADE,
        related_name="claims_made",
    )
    content_type = m.ForeignKey(
        ContentType,
        on_delete=m.CASCADE,
        verbose_name=_("content type"),
        related_name="%(app_label)s_%(class)s_claims",
    )
    object_id = m.IntegerField(
        verbose_name=_("object ID"),
        db_index=True,
    )
    content_object = GenericForeignKey()
    approved = m.BooleanField(
        null=True,
        blank=True,
    )
    reviewed_at = m.DateTimeField(
        null=True,
        blank=True,
    )
    reviewed_by = m.ForeignKey(
        User,
        on_delete=m.SET_NULL,
        null=True,
        blank=True,
        related_name="claims_reviewed",
    )

    @classmethod
    def claims_for(cls, obj):
        model = type(obj)._meta.concrete_model
        return cls.objects.filter(
            content_type__app_label=model._meta.app_label,
            content_type__model=model._meta.model_name,
            object_id=obj.pk,
        )

    def __str__(self):
        if not self.reviewed_at:
            status = "pending review"
        else:
            status = "approved" if self.approved else "rejected"
        return (
            f"Claim by {self.user.display_name()} for {self.content_object} ({status})"
        )

svaudio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models as m
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for sunvox.audio."""

    #: First and last name do not cover name patterns around the globe
    name = m.CharField(
        _("Display Name"),
        blank=True,
        max_length=255,
        help_text=_("Optional, to show a different name than your username."),
    )
    is_moderator = m.BooleanField(default=False)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    feature_as_artist = m.BooleanField(
        default=False,
        help_text=_("Select this to be included in list of artists."),
    )
    auto_publish_uploads = m.BooleanField(
        default=False,
        help_text=_("Select this to make new uploads publicly listed."),
    )
    bio = m.TextField(
        blank=True,
        help_text=_("Limited Markdown supported"),
    )

    def display_name(self):
        return self.name or self.username

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

svaudio/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

svaudio/artists/views.py
from django.views.generic import ListView

from svaudio.users.models import User


class ArtistListView(ListView):

    model = User
    template_name = "artists/artist_list.html"

    def get_queryset(self):
        return super(ArtistListView, self).get_queryset().filter(feature_as_artist=True)


artists_list_view = ArtistListView.as_view()

svaudio/claims/views.py
from datetime import datetime, timezone
from typing import Any, Dict

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView

from ..mixins import ModeratorRequiredMixin
from ..repo.models import Module, Project
from .models import Claim

# [TODO] factor this out into settings
CLAIMS_ALLOWED_MODELS = [
    Module,
    Project,
]


def _get_target_object(content_type_id, object_id):
    content_type = ContentType.objects.get(id=content_type_id)
    cls = content_type.model_class()
    if cls not in CLAIMS_ALLOWED_MODELS:
        raise Http404()
    obj = cls.objects.get(id=object_id)
    if not obj:
        raise Http404()
    return obj


class ModerateView(ModeratorRequiredMixin, ListView):

    template_name = "claims/moderate.html"
    model = Claim

    def get_queryset(self):
        return Claim.objects.filter(reviewed_at=None)


moderate_view = ModerateView.as_view()


def moderate_action_view(request):
    u = request.user
    if not (u.is_authenticated and (u.is_superuser or u.is_moderator)):
        raise Http404()
    claim = get_object_or_404(Claim, pk=request.POST["claim_id"])
    if claim.reviewed_by:
        raise Http404()
    action_type = request.POST["action_type"]
    if action_type == "approve":
        claim.approved = True
    elif action_type == "reject":
        claim.approved = False
    else:
        raise Http404()
    claim.reviewed_by = u
    claim.reviewed_at = datetime.now(tz=timezone.utc)
    claim.save()
    messages.add_message(
        request,
        messages.SUCCESS,
        f'Thank you for moderating "{claim}"',
    )
    return redirect("claims:moderate")


class ObjectClaimListView(LoginRequiredMixin, ListView):

    template_name = "claims/object_claim_list.html"
    model = Claim

    def get_queryset(self):
        content_type_id = self.kwargs["content_type_id"]
        object_id = self.kwargs["object_id"]
        return Claim.objects.filter(
            content_type_id=content_type_id,
            object_id=object_id,
            approved=True,
        )

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        data = super().get_context_data(**kwargs)
        # Find target object.
        data["content_type_id"] = self.kwargs["content_type_id"]
        data["object_id"] = self.kwargs["object_id"]
        target = _get_target_object(data["content_type_id"], data["object_id"])
        data["target"] = target
        # Find any user claim, even if pending.
        user_claim = Claim.claims_for(target).filter(user=self.request.user).first()
        data["user_claim"] = user_claim
        return data


object_claim_list_view = ObjectClaimListView.as_view()


def object_claim_create_view(request, content_type_id, object_id):
    if not request.user.is_authenticated:
        raise Http404()
    target = _get_target_object(content_type_id, object_id)
    redirect_to_claim_list = redirect(
        "claims:object-claim-list",
        content_type_id=content_type_id,
        object_id=object_id,
    )
    user_claim = Claim.claims_for(target).filter(user=request.user).first()
    if user_claim:  # already exists?
        return redirect_to_claim_list
    p = request.POST.get
    if ("yes", "yes", "yes") != (p("ownerAck"), p("reviewAck"), p("abuseAck")):
        messages.add_message(
            request,
            messages.WARNING,
            "Please acknowledge all three items to claim ownership.",
        )
        return redirect_to_claim_list
    Claim.objects.create(user=request.user, content_object=target)
    messages.add_message(
        request,
        messages.SUCCESS,
        "Thank you! Your ownership claim was submitted and will now be reviewed.",
    )
    return redirect_to_claim_list

svaudio/tags/views.py
from django.views.generic import DetailView, ListView

from . import models as m


class TagListView(ListView):

    model = m.Tag
    template_name = "tags/tag_list.html"


tag_list_view = TagListView.as_view()


class TagDetailView(DetailView):

    model = m.Tag
    template_name = "tags/tag_detail.html"


tag_detail_view = TagDetailView.as_view()

svaudio/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

svaudio/users/views.py
from dataclasses import dataclass

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.functions import Lower
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


@dataclass
class Redirection(Exception):
    url: str


class UserDetailView(DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Redirection as r:
            return redirect(r.url)

    def get_object(self, queryset=None):
        queryset = queryset or self.model
        username = self.kwargs["username"]
        obj = queryset.objects.filter(username=username).first()
        if obj:
            return obj
        user = (
            queryset.objects.annotate(username_lower=Lower("username"))
            .filter(username_lower=username.lower())
            .first()
        )
        if not user:
            raise Http404()
        url = reverse("users:detail", kwargs={"username": user.username})
        raise Redirection(url=url)


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name", "feature_as_artist", "auto_publish_uploads", "bio"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

svaudio/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}(Untitled){% endblock title %} — sunvox.audio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The world's best unofficial library of SunVox resources">
    <meta name="author" content="The SunVox Community">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}

      <!-- Vendor dependencies bundled as one file-->
      {% compress js %}
      <script defer src="{% static 'js/vendors.js' %}"></script>
      {% endcompress %}


      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script defer src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="ms-3 navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/favicons/favicon.ico' %}" alt="sunvox.audio logo" height="32" width="32">
            sunvox.audio
          </a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item {% block nav_active_modules %}{% endblock %}">
                <a class="nav-link" href="{% url 'repo:module-list' %}">Modules</a>
              </li>
              <li class="nav-item {% block nav_active_projects %}{% endblock %}">
                <a class="nav-link" href="{% url 'repo:project-list' %}">Projects</a>
              </li>
              <li class="nav-item {% block nav_active_artists %}{% endblock %}">
                <a class="nav-link" href="{% url 'artists:artist-list' %}">Artists</a>
              </li>
              <li class="nav-item {% block nav_active_tags %}{% endblock %}">
                <a class="nav-link" href="{% url 'tags:tag-list' %}">Tags</a>
              </li>
              {% if request.user.is_superuser or request.user.is_moderator %}
                <li class="nav-item {% block nav_active_claims %}{% endblock %}">
                  <a class="nav-link" href="{% url 'claims:moderate' %}">Claims</a>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item {% block nav_active_profile %}{% endblock %}">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </div>

    <div class="container mb-5">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show">{{ message }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <div class="border-top">
      <div class="container small">
        <div class="row mt-4">
          <div class="col">
            <ul class="list-unstyled">
              <li>&copy; MetraSynth (site code &amp; design)</li>
              <li>&copy; contributors (site content)</li>
              <li>
                <ul class="list-inline">
                  <li class="list-inline-item">
                    <a href="https://github.com/metrasynth/svaudio/">GitHub</a>
                  </li>
                  <li class="list-inline-item">
                    <a href="mailto:contact@sunvox.audio">Email</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="col">
            <ul class="list-unstyled">
              <li><a href="/">Home</a></li>
              <li><a href="/about/">About</a></li>
              <li><a href="/privacy/">Privacy</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>