config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import redirect
from django.urls import include, path
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from rest_framework.authtoken.views import obtain_auth_token


def favicon(request):
    return redirect(
        staticfiles_storage.url("images/favicons/favicon.ico"),
        permanent=True,
    )


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("svaudio.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("activity/", include("actstream.urls")),
    path("comments/", include("django_comments.urls")),
    # Redirect to favicon
    path("favicon.ico", favicon),
    # Your stuff: custom urls includes go here
    path("", include("svaudio.artists.urls", namespace="artists")),
    path("", include("svaudio.repo.urls", namespace="repo")),
    path("", include("svaudio.tags.urls", namespace="tags")),
    path("claims/", include("svaudio.claims.urls", namespace="claims")),
    # Flatpages go last
    path("", flatpages_views.flatpage, {"url": "/"}, name="home"),
    path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # GraphQL base url
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

svaudio/claims/urls.py
from django.urls import path

from .views import (
    moderate_action_view,
    moderate_view,
    object_claim_create_view,
    object_claim_list_view,
)

app_name = "claims"
urlpatterns = [
    path(
        "moderate/",
        view=moderate_view,
        name="moderate",
    ),
    path(
        "moderate/~action/",
        view=moderate_action_view,
        name="moderate-action",
    ),
    path(
        "<int:content_type_id>/<int:object_id>/",
        view=object_claim_list_view,
        name="object-claim-list",
    ),
    path(
        "<int:content_type_id>/<int:object_id>/~create/",
        view=object_claim_create_view,
        name="object-claim-create",
    ),
]

svaudio/repo/urls.py
from django.urls import path

from svaudio.repo.views import (
    location_submit_api_view,
    location_submit_view,
    module_add_tag_view,
    module_detail_view,
    module_list_view,
    module_remove_tagged_item_view,
    module_update_view,
    project_add_tag_view,
    project_detail_view,
    project_list_view,
    project_remove_tagged_item_view,
    project_update_view,
)

app_name = "repo"
urlpatterns = [
    path(
        "locations/submit/",
        view=location_submit_view,
        name="location-submit",
    ),
    path(
        "locations/submit/api/",
        view=location_submit_api_view,
        name="location-submit-api",
    ),
    path(
        "modules/",
        view=module_list_view,
        name="module-list",
    ),
    path(
        "modules/<str:hash>/",
        view=module_detail_view,
        name="module-detail",
    ),
    path(
        "modules/<str:hash>/~add-tag/",
        view=module_add_tag_view,
        name="module-add-tag",
    ),
    path(
        "modules/<str:hash>/~remove-tagged-item/",
        view=module_remove_tagged_item_view,
        name="module-remove-tagged-item",
    ),
    path(
        "modules/<str:hash>/~update/",
        view=module_update_view,
        name="module-update",
    ),
    path(
        "projects/",
        view=project_list_view,
        name="project-list",
    ),
    path(
        "projects/<str:hash>/",
        view=project_detail_view,
        name="project-detail",
    ),
    path(
        "projects/<str:hash>/~add-tag/",
        view=project_add_tag_view,
        name="project-add-tag",
    ),
    path(
        "projects/<str:hash>/~remove-tagged-item/",
        view=project_remove_tagged_item_view,
        name="project-remove-tagged-item",
    ),
    path(
        "projects/<str:hash>/~update/",
        view=project_update_view,
        name="project-update",
    ),
]

svaudio/tags/urls.py
from django.urls import path

from svaudio.tags.views import tag_detail_view, tag_list_view

app_name = "tags"
urlpatterns = [
    path(
        "tags/",
        view=tag_list_view,
        name="tag-list",
    ),
    path(
        "tags/<str:slug>/",
        view=tag_detail_view,
        name="tag-detail",
    ),
]

svaudio/users/urls.py
from django.urls import path

from svaudio.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

svaudio/artists/views.py
from django.views.generic import ListView

from svaudio.users.models import User


class ArtistListView(ListView):

    model = User
    template_name = "artists/artist_list.html"

    def get_queryset(self):
        return super(ArtistListView, self).get_queryset().filter(feature_as_artist=True)


artists_list_view = ArtistListView.as_view()

svaudio/claims/views.py
from datetime import datetime, timezone
from typing import Any, Dict

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView

from ..mixins import ModeratorRequiredMixin
from ..repo.models import Module, Project
from .models import Claim

# [TODO] factor this out into settings
CLAIMS_ALLOWED_MODELS = [
    Module,
    Project,
]


def _get_target_object(content_type_id, object_id):
    content_type = ContentType.objects.get(id=content_type_id)
    cls = content_type.model_class()
    if cls not in CLAIMS_ALLOWED_MODELS:
        raise Http404()
    obj = cls.objects.get(id=object_id)
    if not obj:
        raise Http404()
    return obj


class ModerateView(ModeratorRequiredMixin, ListView):

    template_name = "claims/moderate.html"
    model = Claim

    def get_queryset(self):
        return Claim.objects.filter(reviewed_at=None)


moderate_view = ModerateView.as_view()


def moderate_action_view(request):
    u = request.user
    if not (u.is_authenticated and (u.is_superuser or u.is_moderator)):
        raise Http404()
    claim = get_object_or_404(Claim, pk=request.POST["claim_id"])
    if claim.reviewed_by:
        raise Http404()
    action_type = request.POST["action_type"]
    if action_type == "approve":
        claim.approved = True
    elif action_type == "reject":
        claim.approved = False
    else:
        raise Http404()
    claim.reviewed_by = u
    claim.reviewed_at = datetime.now(tz=timezone.utc)
    claim.save()
    messages.add_message(
        request,
        messages.SUCCESS,
        f'Thank you for moderating "{claim}"',
    )
    return redirect("claims:moderate")


class ObjectClaimListView(LoginRequiredMixin, ListView):

    template_name = "claims/object_claim_list.html"
    model = Claim

    def get_queryset(self):
        content_type_id = self.kwargs["content_type_id"]
        object_id = self.kwargs["object_id"]
        return Claim.objects.filter(
            content_type_id=content_type_id,
            object_id=object_id,
            approved=True,
        )

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        data = super().get_context_data(**kwargs)
        # Find target object.
        data["content_type_id"] = self.kwargs["content_type_id"]
        data["object_id"] = self.kwargs["object_id"]
        target = _get_target_object(data["content_type_id"], data["object_id"])
        data["target"] = target
        # Find any user claim, even if pending.
        user_claim = Claim.claims_for(target).filter(user=self.request.user).first()
        data["user_claim"] = user_claim
        return data


object_claim_list_view = ObjectClaimListView.as_view()


def object_claim_create_view(request, content_type_id, object_id):
    if not request.user.is_authenticated:
        raise Http404()
    target = _get_target_object(content_type_id, object_id)
    redirect_to_claim_list = redirect(
        "claims:object-claim-list",
        content_type_id=content_type_id,
        object_id=object_id,
    )
    user_claim = Claim.claims_for(target).filter(user=request.user).first()
    if user_claim:  # already exists?
        return redirect_to_claim_list
    p = request.POST.get
    if ("yes", "yes", "yes") != (p("ownerAck"), p("reviewAck"), p("abuseAck")):
        messages.add_message(
            request,
            messages.WARNING,
            "Please acknowledge all three items to claim ownership.",
        )
        return redirect_to_claim_list
    Claim.objects.create(user=request.user, content_object=target)
    messages.add_message(
        request,
        messages.SUCCESS,
        "Thank you! Your ownership claim was submitted and will now be reviewed.",
    )
    return redirect_to_claim_list

svaudio/repo/views.py
import json
from typing import Any, Dict

from actstream import action
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import DatabaseError
from django.db.models import Model
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from ..claims.models import Claim
from ..tags.models import Tag, TaggedItem
from ..verbs import Verb
from . import models as m


class LocationsSubmitView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = m.Location
    fields = ["url"]
    success_message = _("URL successfully submitted")
    template_name = "repo/location_submit.html"

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super(LocationsSubmitView, self).form_valid(form)

    def get_success_url(self) -> str:
        return reverse("repo:location-submit")


location_submit_view = LocationsSubmitView.as_view()


@csrf_exempt
def location_submit_api_view(request):
    if request.method != "POST":
        raise Http404()
    if request.content_type != "application/json":
        raise Http404()
    body = json.loads(request.body) or {}
    private_key = body.get("key")
    if private_key != settings.SVAUDIO_REPO_API_SECRET_KEY:
        raise Http404()
    url = body.get("url")
    metadata = body.get("metadata")
    if not url:
        raise Http404()
    try:
        m.Location.objects.create(url=url, metadata=metadata)
        response = {"submitted": True}
    except DatabaseError:
        response = {"submitted": False}
    return HttpResponse(content=json.dumps(response), content_type="application/json")


class ModulesListView(ListView):

    model = m.Module
    queryset = m.Module.objects.filter(listed=True).order_by("-file__cached_at")


module_list_view = ModulesListView.as_view()


class GetByHashMixin:
    model: Model
    kwargs: Dict[str, Any]

    def get_object(self, queryset=None):
        return self.model.objects.get(file__hash=self.kwargs.get("hash"))


class ModulesDetailView(GetByHashMixin, SuccessMessageMixin, DetailView):

    model = m.Module


module_detail_view = ModulesDetailView.as_view()


class ModuleUpdateView(GetByHashMixin, UpdateView):

    model = m.Module
    template_name = "repo/module_update.html"
    fields = [
        "alt_name",
        "description",
        "listed",
    ]

    def get_object(self, queryset=None):
        obj = super(ModuleUpdateView, self).get_object(queryset)
        if not obj:
            raise Http404()
        user_claim = (
            Claim.claims_for(obj)
            .filter(
                user=self.request.user,
                approved=True,
            )
            .first()
        )
        if not user_claim:
            raise Http404()
        return obj

    def get_success_url(self) -> str:
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f"Saved changes to {self.object}",
        )
        return self.object.get_absolute_url()


module_update_view = ModuleUpdateView.as_view()


class ProjectsListView(ListView):

    model = m.Project
    queryset = m.Project.objects.filter(listed=True).order_by("-file__cached_at")


project_list_view = ProjectsListView.as_view()


class ProjectsDetailView(GetByHashMixin, DetailView):

    model = m.Project


project_detail_view = ProjectsDetailView.as_view()


class ProjectUpdateView(GetByHashMixin, SuccessMessageMixin, UpdateView):

    model = m.Project
    template_name = "repo/project_update.html"
    fields = [
        "alt_name",
        "description",
        "listed",
    ]

    def get_object(self, queryset=None):
        obj = super(ProjectUpdateView, self).get_object(queryset)
        if not obj:
            raise Http404()
        user_claim = (
            Claim.claims_for(obj)
            .filter(
                user=self.request.user,
                approved=True,
            )
            .first()
        )
        if not user_claim:
            raise Http404()
        return obj

    def get_success_url(self) -> str:
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f"Saved changes to {self.object}",
        )
        return self.object.get_absolute_url()


project_update_view = ProjectUpdateView.as_view()


def module_add_tag_view(request, hash):
    return _add_tag_view("module", request, hash)


def module_remove_tagged_item_view(request, hash):
    return _remove_tagged_item_view("module", request, hash)


def project_add_tag_view(request, hash):
    return _add_tag_view("project", request, hash)


def project_remove_tagged_item_view(request, hash):
    return _remove_tagged_item_view("project", request, hash)


def _add_tag_view(modelname, request, hash):
    user = request.user
    if not user.is_authenticated:
        return redirect(f"repo:{modelname}-detail", hash=hash)
    model = {"module": m.Module, "project": m.Project}[modelname]
    obj = get_object_or_404(model, file__hash=hash)
    tags = request.POST["tags"]
    tags = tags.split(",")
    tags = [t.strip().lower() for t in tags]
    tags = [t[1:] if t[0:1] == "#" else t for t in tags]
    tags = {t for t in tags if t}
    existing_tags = {t.name for t in obj.tags.all()}
    new_tags = list(sorted(tags - existing_tags))
    obj.tags.add_by_user(user, *new_tags)
    for new_tag in new_tags:
        action.send(
            sender=user,
            verb=Verb.ADDED_TAG,
            action_object=Tag.objects.get(name=new_tag),
            target=obj,
        )
    count = len(new_tags)
    messages.add_message(
        request,
        messages.SUCCESS,
        f"You added {count} new tag{'s' if count != 1 else ''}. Thanks!",
    )
    obj.clear_caches()
    return redirect(f"repo:{modelname}-detail", hash=hash)


def _remove_tagged_item_view(modelname, request, hash):
    user = request.user
    if not user.is_authenticated:
        return redirect(f"repo:{modelname}-detail", hash=hash)
    model = {"module": m.Module, "project": m.Project}[modelname]
    obj = get_object_or_404(model, file__hash=hash)
    tagged_item_id = request.POST["tagged_item_id"]
    tagged_items = obj.tagged_items.filter(id=tagged_item_id)
    tagged_item: TaggedItem
    for tagged_item in tagged_items:
        if request.user.is_moderator or (
            tagged_item.recently_added() and tagged_item.added_by == user
        ):
            messages.add_message(
                request,
                messages.SUCCESS,
                f"You removed the {tagged_item.tag.name!r} tag.",
            )
            action.send(
                sender=user,
                verb=Verb.REMOVED_TAG,
                action_object=tagged_item.tag,
                target=obj,
            )
            tagged_item.delete()
            obj.clear_caches()
            break
    return redirect(f"repo:{modelname}-detail", hash=hash)

svaudio/templates/repo/_add_tag_inline_form.html
{# params: request,add_tag_url_name,object #}
{% if request.user.is_authenticated %}
  <form method="post" action="{% url add_tag_url_name hash=object.file.hash %}" class="form-inline">
    {% csrf_token %}
    <div class="input-group mb-2 mr-sm-2 input-group-sm">
      <div class="input-group-prepend">
        <div class="input-group-text">#</div>
      </div>
      <input type="text" class="form-control" id="addTagsInput" name="tags" placeholder="tag1,tag2,...">
    </div>
    <button class="btn btn-primary mb-2 btn-sm" type="submit">Add Tag(s)</button>
  </form>
{% endif %}

svaudio/templates/repo/_byline.html
{# params: claims resource_type #}
<p>
  SunVox {{ resource_type }} {% if claims %}{% for claim in claims %}{% if forloop.first %}by{% else %},{% endif %} <a href="{% url 'users:detail' username=claim.user.username %}">{{ claim.user.display_name }}</a>{% endfor %}{% endif %}
</p>

svaudio/templates/repo/_comments.html
{% load comments %}

<h2>Comments</h2>

{% render_comment_form for object %}

{% render_comment_list for object %}

svaudio/templates/repo/_file_details.html
{# params: object #}
<h2>File details</h2>

<ul>
  {% if object.name != object.display_name %}
    <li>Original name: {{ object.name }}</li>
  {% endif %}
  <li>Hash: {{ object.file.hash }}</li>
  <li>Size: {{ object.file.size }}</li>
  {% with object.file.media_url as media_url %}
    {% if media_url %}
      <li><a href="{{ media_url }}">Download cached copy</a></li>
    {% endif %}
  {% endwith %}
</ul>

svaudio/templates/repo/_module_table.html
{# params: object_list tag_items #}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Module</th>
      <th scope="col">Added</th>
    </tr>
  </thead>
  <tbody>
    {% for module in object_list %}
      {% if tag_items %}
        {% with module.content_object as module %}
          {% include "repo/_module_table_row.html" %}
        {% endwith %}
      {% else %}
        {% include "repo/_module_table_row.html" %}
      {% endif %}
    {% empty %}
      <tr>
        <td colspan="2">(No modules)</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

svaudio/templates/repo/_ownership.html
{# params: claims,object,request #}
{% load claims %}
{% if request.user.is_authenticated %}
  <hr>

  {% claim_for_object_by_user object request.user as claim %}

  {% if claim %}
    {% if not claim.reviewed_at %}
      <p>
        {% if claims.count > 1 %}
          You are a co-owner of this {{ type }} (pending review).
        {% else %}
          You are the owner of this {{ type }} (pending review).
        {% endif %}
      </p>
    {% elif claim.approved %}
      <p>
        {% if claims.count > 1 %}
          You are a co-owner of this {{ type }}.
        {% else %}
          You are the owner of this {{ type }}.
        {% endif %}
      </p>
      <p>
        <a class="btn btn-primary" href="{{ object.get_update_url }}">Edit {{ type }}</a>
      </p>
    {% else %}
      <p>
        Note: Your request to claim ownership of this {{ type }} was rejected.
      </p>
    {% endif %}
  {% else %}
    {% if claims.count == 1 %}
      <p>There is {{ claims.count }} owner of this {{ type }}.</p>
    {% else %}
      <p>There are {{ claims.count }} owners of this {{ type }}.</p>
    {% endif %}
    {% with object|content_type as ctype %}
      {% url "claims:object-claim-list" content_type_id=ctype.id object_id=object.id as claims_url %}
      {% if claims.count %}
        <p>
          If you are a co-author or co-collaborator for this {{ type }},
          you can also <a href="{{ claims_url }}">claim ownership</a>.
        </p>
      {% else %}
        <p>
          If you are an author or collaborator for this {{ type }},
          you can <a href="{{ claims_url }}">claim ownership</a>.
        </p>
      {% endif %}
    {% endwith %}
  {% endif %}

{% endif %}

svaudio/templates/repo/_project_table.html
{# params: object_list tag_items #}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Project</th>
      <th scope="col">Added</th>
    </tr>
  </thead>
  <tbody>
    {% for project in object_list %}
      {% if tag_items %}
        {% with project.content_object as project %}
          {% include "repo/_project_table_row.html" %}
        {% endwith %}
      {% else %}
        {% include "repo/_project_table_row.html" %}
      {% endif %}
    {% empty %}
      <tr>
        <td colspan="2">(No projects)</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

svaudio/templates/repo/_project_table_row.html
{# params: project #}
{% load cache %}
<tr>
  {% cache None project-table-row project.pk %}
    <td>
      <span>
        <a href="{{ project.get_absolute_url }}">{{ project.display_name }}</a>
      </span>
      {% include "repo/_tag_links.html" with object=project modelname="project" %}
    </td>
  {% endcache %}
  <td>
    {{ project.file.cached_at }}
  </td>
</tr>

svaudio/templates/repo/_tag_links.html
{# params: object modelname #}
{% load cache %}
{% cache None object-tag-list modelname object.pk %}
  <ul class="list-inline">
    {% for tag in object.tags.all %}
      <li class="list-inline-item">
        <a href="{% url 'tags:tag-detail' slug=tag.slug %}"><span class="badge bg-primary">#{{ tag.name }}</span></a>
      </li>
    {% endfor %}
  </ul>
{% endcache %}

svaudio/templates/repo/_tag_links_editable.html
{# params: object modelname request #}
{% with user=request.user %}
  {% if not user.is_authenticated %}
    {% include "repo/_tag_links.html" %}
  {% else %}
    <ul class="list-inline">
      {% for tag_item in object.tagged_items.all %}
        {% with tag=tag_item.tag added_by=tag_item.added_by recently_added=tag_item.recently_added %}
          <li class="list-inline-item">
            <a href="{% url 'tags:tag-detail' slug=tag.slug %}"><span class="badge bg-primary">#{{ tag.name }}</span></a>
            {% if user.is_moderator or recently_added and added_by == user %}
              <span onclick="submitHiddenTagRemoveForm({{ tag_item.id }}, '{{ tag.slug }}')">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-x-square-fill" viewBox="0 0 16 16">
                  <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                </svg>
              </span>
            {% endif %}
          </li>
        {% endwith %}
      {% endfor %}
    </ul>
    <form name="hiddenTagRemoveForm" action="{% url 'repo:project-remove-tagged-item' hash=object.file.hash %}" method="post">
      <input type="hidden" name="tagged_item_id" id="hiddenTagRemoveForm_tagged_item_id" value="">
      {% csrf_token %}
    </form>
  {% endif %}
{% endwith %}

svaudio/templates/repo/module_detail.html
{% extends "base.html" %}
{% load claims static markdownify %}

{% block title %}Module: {{ object.display_name }}{% endblock %}

{% block nav_active_modules %}active{% endblock %}

{% block content %}
  <h1 class="resource-name-heading">{{ object.display_name }}</h1>

  {% approved_claims_for_object object as claims %}

  {% include "repo/_byline.html" with resource_type="module" %}

  {% if not object.listed %}
    <p>Note: The owner of this module has marked it as unlisted.</p>
  {% endif %}

  <p>
    {% include "repo/_tag_links_editable.html" with modelname="module" object=object %}
  </p>

  <div>
    {% include "repo/_add_tag_inline_form.html" with add_tag_url_name="repo:module-add-tag" %}
  </div>

  {% if object.description %}
    <hr>
    <div>
      {{ object.description|markdownify:"description" }}
    </div>
  {% endif %}

  <hr>

  {% include "repo/_file_details.html" %}

  <hr>

  {% include "repo/_comments.html" %}

  <hr>

  {% include "repo/_found_at.html" with type="module" %}

  {% include "repo/_ownership.html" with type="module" %}

{% endblock content %}

{% block inline_javascript %}
  <script type="application/javascript">
    function submitHiddenTagRemoveForm(tagged_item_id, slug) {
      if (!confirm("Remove tag " + slug + "?")) {
        return null
      }
      let hiddenTagRemoveForm_tagged_item_id = document.getElementById("hiddenTagRemoveForm_tagged_item_id")
      hiddenTagRemoveForm_tagged_item_id.setAttribute("value", tagged_item_id)
      document.forms['hiddenTagRemoveForm'].submit()
      return null
    }
  </script>
{% endblock %}

svaudio/templates/repo/module_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Modules{% endblock %}

{% block nav_active_modules %}active{% endblock %}

{% block content %}

  <h1>Modules</h1>

  {% include "repo/_module_table.html" %}

{% endblock content %}

svaudio/templates/repo/module_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Editing module: {{ object.display_name }}</h1>

  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{% endblock %}